[game]
name = "WordMon Go"
version = "0.2.0"

[rarityWeights]
Common = 80
Rare = 18
Legendary = 2

[xpRewards]
Common = 5
Rare = 20
Legendary = 100

[spawner]
intervalSeconds = 10
autoFleeAfterSeconds = 5

[level]
base = 1
xpPerLevel = 100